prefix = "!"
version = "3.0.0"
development = true
[db]
uri = ""
[logs]
channelId = '895959965469134858'
guildId = '891367004903182336'
[misc]
ownerId = '774292293020155906'
botId = '893319907981283340'
[bot.gateway]
token = ""
intents = [
  "Guilds",
  "GuildMessages",
  "GuildMessageReactions",
  "GuildEmojis",
  "DirectMessages",
]
